In [22]:
from math import *

import numpy as np
import scipy as sp

import scipy.linalg

np.set_printoptions(precision=3)

In [13]:
def gen_selftrans(n):
    a = np.random.randn(n, n) * 5
    a = (a + a.T) / 2
    return a

def lower_triangle(n):
    a = np.random.randn(n, n) * 5
    for i in range(n):
        for j in range(i + 1, n):
            a[i, j] = 0
    return a

n = 5
a = gen_selftrans(n)

In [14]:
print(a)
print(a.dot(np.eye(n).T))

[[ 3.96  3.7   1.42  1.31  5.51]
 [ 3.7  -0.29 -6.93  7.28 -3.17]
 [ 1.42 -6.93 -1.99  2.26  4.76]
 [ 1.31  7.28  2.26  2.05 -2.92]
 [ 5.51 -3.17  4.76 -2.92 -6.29]]
[[ 3.96  3.7   1.42  1.31  5.51]
 [ 3.7  -0.29 -6.93  7.28 -3.17]
 [ 1.42 -6.93 -1.99  2.26  4.76]
 [ 1.31  7.28  2.26  2.05 -2.92]
 [ 5.51 -3.17  4.76 -2.92 -6.29]]


In [4]:
n = 2
a = np.array([[0, 1], [1, 0]])
print(a)

[[0 1]
 [1 0]]


In [7]:
a

array([[0, 1],
       [1, 0]])

In [21]:
current_a = a.copy()
guess = a.copy()
current_M = np.eye(n, n)

for i in range(n):
    if not current_a[i, i]:
        max_ind = i
        for j in range(i + 1, n):
            if abs(current_a[i][j]) > abs(current_a[i][max_ind]):
                max_ind = current_a[i][j]
        M = np.eye(n)
#         M[max_ind, max_ind] = 0
#         M[i, i] = 0
#         M[i, max_ind] = 1
        M[max_ind, i] = 1
        
        current_M = current_M.dot(M)
        current_a = M.T.dot(current_a.dot(M))
        print('M:\n{}'.format(M))
        print('a:\n{}'.format(current_a))
        print()     
        print()
        print()

        
    trans = current_a[i, :].copy() / -(current_a[i, i]) / math.sqrt(current_a[i, i])
    trans[i] *= -1

    M = np.vstack([np.eye(i, n), trans, np.eye(n - i - 1, n, i + 1)])
    current_M = current_M.dot(M)
    current_a = M.T.dot(current_a.dot(M))
    print('M:\n{}'.format(M))
    print('all_M:\n{}'.format(current_M))
    print('a:\n{}'.format(current_a))
    print()
    print()
    print()
    print()
        
np.set_printoptions(precision=2)
print(current_a)
print(current_M.T.dot(a.dot(current_M)))
    
# print(M.dot(a.dot(M.T)))
# print(M.T.dot(a.dot(M)))
# print()
# print(Mi.dot(a.dot(Mi.T)))
# print(Mi.T.dot(a.dot(Mi)))

NameError: name 'math' is not defined

In [18]:
current_a = a.copy()
guess = a.copy()
current_M = np.eye(n, n)

for i in range(n):
    trans = guess[i, :].copy() / -guess[i, i]
    trans[i] *= -1
    
    M = np.vstack([np.eye(i, n), trans, np.eye(n - i - 1, n, i + 1)])
#     Mi = np.linalg.inv(M)
    
    for j in range(i+ 1, n):
        for k in range(n):
            guess[j, k] -= guess[i, j] * guess[i, k] / guess[i, i]
    guess[i, :i] = 0
    guess[i, i + 1:] = 0
    guess[:i, i] = 0
    guess[i + 1:, i] = 0

    current_M = current_M.dot(M)
    print(M)
    print()
    print(current_M)
    print()
    print()
    print()
    print()


    
print()
np.set_printoptions(precision=2)
print(current_M.T.dot(a.dot(current_M)))
    
# print(M.dot(a.dot(M.T)))
# print(M.T.dot(a.dot(M)))
# print()
# print(Mi.dot(a.dot(Mi.T)))
# print(Mi.T.dot(a.dot(Mi)))

[[ 1.   -0.93 -0.36 -0.33 -1.39]
 [ 0.    1.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.  ]
 [ 0.    0.    0.    1.    0.  ]
 [ 0.    0.    0.    0.    1.  ]]

[[ 1.   -0.93 -0.36 -0.33 -1.39]
 [ 0.    1.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.  ]
 [ 0.    0.    0.    1.    0.  ]
 [ 0.    0.    0.    0.    1.  ]]




[[ 1.    0.    0.    0.    0.  ]
 [ 0.    1.   -2.21  1.62 -2.22]
 [ 0.    0.    1.    0.    0.  ]
 [ 0.    0.    0.    1.    0.  ]
 [ 0.    0.    0.    0.    1.  ]]

[[ 1.   -0.93  1.7  -1.84  0.68]
 [ 0.    1.   -2.21  1.62 -2.22]
 [ 0.    0.    1.    0.    0.  ]
 [ 0.    0.    0.    1.    0.  ]
 [ 0.    0.    0.    0.    1.  ]]




[[ 1.    0.    0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.  ]
 [-0.   -0.    1.    0.74 -1.34]
 [ 0.    0.    0.    1.    0.  ]
 [ 0.    0.    0.    0.    1.  ]]

[[ 1.   -0.93  1.7  -0.59 -1.6 ]
 [ 0.    1.   -2.21 -0.01  0.74]
 [ 0.    0.    1.    0.74 -1.34]
 [ 0.    0.    0.    1.    0.  ]
 [ 0.    0.    0.    0.    